// Single import point for database types. `database.types.ts` is generated by `npm run db:types`
// and must never be hand-edited; add schema-derived aliases here instead.
export type { Database, Json } from "@/db/database.types";
