// Smoke test: proves the built app, the Cloudflare adapter, the Supabase auth flow and the create-group flow work together,
// and that the database app-key gate judges direct Data API calls.
// Zero dependencies on purpose. Run against a live server and local Supabase: `npm run smoke` (reads `.env`; BASE_URL
// defaults to http://localhost:4321).

import { randomBytes, randomUUID } from "node:crypto";

const BASE_URL = process.env.BASE_URL ?? "http://localhost:4321";
// The gate steps call Supabase directly, bypassing the app, with the same values the app uses.
const { SUPABASE_URL, SUPABASE_KEY, SUPABASE_APP_KEY } = process.env;
if (!SUPABASE_URL || !SUPABASE_KEY || !SUPABASE_APP_KEY) {
  console.error("SUPABASE_URL, SUPABASE_KEY and SUPABASE_APP_KEY must be set (npm run smoke reads them from .env)");
  process.exit(1);
}
const email = `smoke-${Date.now()}@example.com`;
const password = "Smoke-Test-Passw0rd!";
// The second user joins group A through the invite link.
const email2 = `smoke-joiner-${Date.now()}@example.com`;
const jar = new Map();
const stamp = Date.now();
const groupA = `Smoke household A ${stamp}`;
const groupB = `Smoke household B ${stamp}`;
// Ids of the groups created by the run, in creation order; later steps read them.
const groupIds = [];
// Token of the invite generated by the run; the invite-flow steps read it.
let inviteToken;
const INVITE_LINK = /\/invite\/([A-Za-z0-9_-]{43})(?![A-Za-z0-9_-])/;
const GROUP_PAGE = /^\/groups\/([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})$/;

function cookieHeader() {
  return [...jar.entries()].map(([k, v]) => `${k}=${v}`).join("; ");
}

function storeCookies(response) {
  for (const raw of response.headers.getSetCookie()) {
    const [pair, ...attrs] = raw.split(";");
    const [name, ...rest] = pair.split("=");
    const expired = attrs.some((a) => /max-age=0/i.test(a.trim()));
    if (expired) jar.delete(name.trim());
    else jar.set(name.trim(), rest.join("="));
  }
}

async function request(path, { method = "GET", form } = {}) {
  const response = await fetch(BASE_URL + path, {
    method,
    redirect: "manual",
    headers: {
      Cookie: cookieHeader(),
      Origin: BASE_URL,
      ...(form ? { "Content-Type": "application/x-www-form-urlencoded" } : {}),
    },
    body: form ? new URLSearchParams(form).toString() : undefined,
  });
  storeCookies(response);
  return { status: response.status, location: response.headers.get("location") ?? "", body: await response.text() };
}

function bodyContains(...texts) {
  return (actual) => {
    const missing = texts.filter((text) => !actual.body.includes(text));
    return missing.length ? `body is missing ${missing.map((text) => JSON.stringify(text)).join(", ")}` : true;
  };
}

// A created group redirects to its own page, with an id no earlier step has seen.
function checkNewGroupPage(actual) {
  const match = GROUP_PAGE.exec(actual.location);
  if (!match) return `location is not /groups/<uuid>: ${actual.location}`;
  if (groupIds.includes(match[1])) return `group id ${match[1]} was already used`;
  groupIds.push(match[1]);
  return true;
}

// Steps on group A need its id; without it they fail instead of silently requesting /groups/undefined.
function requestGroupA() {
  if (groupIds[0] === undefined) return Promise.resolve({ status: 0, location: "(group A was not created)", body: "" });
  return request(`/groups/${groupIds[0]}`);
}

// Asserts the Google sign-in redirect without contacting Google: Supabase's authorize URL, the
// callback as redirect_to, a PKCE challenge, and the code-verifier cookie the callback reads.
function checkInviteGroupPage(groupId) {
  return (actual) => (actual.location === `/groups/${groupId}` ? true : `location is ${actual.location}`);
}

// The group page shows the link exactly once and keeps it out of any cache.
function checkInviteShown(actual) {
  const match = INVITE_LINK.exec(actual.body);
  if (!match) return "body has no /invite/<43 chars> link";
  inviteToken = match[1];
  return true;
}

function checkInviteHidden(actual) {
  if (inviteToken === undefined) return "no invite token was saved";
  return actual.body.includes(`/invite/${inviteToken}`) ? "invite link is shown again" : true;
}

function generateInviteA() {
  if (groupIds[0] === undefined) return Promise.resolve({ status: 0, location: "(group A was not created)", body: "" });
  return request(`/api/groups/${groupIds[0]}/invites`, { method: "POST" });
}

// Invite-flow steps need the token saved by "group page shows the invite link once"; without it they fail
// instead of silently requesting /invite/undefined.
function requestInvite(path, options) {
  if (inviteToken === undefined)
    return Promise.resolve({ status: 0, location: "(no invite token was saved)", body: "" });
  return request(path.replace("<token>", inviteToken), options);
}

function checkPendingInviteCookie(_actual, cookies) {
  return cookies.get("sd_pending_invite") === inviteToken ? true : "no sd_pending_invite cookie holding the token";
}

function checkInviteLocation(suffix = "") {
  return (actual) => (actual.location === `/invite/${inviteToken}${suffix}` ? true : `location is ${actual.location}`);
}

function checkGroupALocation(actual) {
  return actual.location === `/groups/${groupIds[0]}` ? true : `location is ${actual.location}`;
}

// Calls a persistence function straight through the Data API, as a user holding their token could.
async function directRpc(name, { token, headers = {} }) {
  const response = await fetch(`${SUPABASE_URL}/rest/v1/rpc/${name}`, {
    method: "POST",
    headers: { apikey: SUPABASE_KEY, Authorization: `Bearer ${token}`, "Content-Type": "application/json", ...headers },
    body: "{}",
  });
  return { status: response.status, location: "", body: await response.text() };
}

// The first smoke user's own access token, taken from Supabase Auth directly, not from the app.
async function firstUserToken() {
  const response = await fetch(`${SUPABASE_URL}/auth/v1/token?grant_type=password`, {
    method: "POST",
    headers: { apikey: SUPABASE_KEY, "Content-Type": "application/json" },
    body: JSON.stringify({ email, password }),
  });
  // Fail loudly here, so a sign-in problem does not surface later as a confusing 401 from the gate steps.
  if (!response.ok) throw new Error(`password grant for the first smoke user failed with ${response.status}`);
  const session = await response.json();
  return session.access_token;
}

// The gate judges `x-app-key` on every Data API request; only the app's key gets through.
async function firstUserCallsDirectly(appKey) {
  return directRpc("list_my_groups", {
    token: await firstUserToken(),
    headers: appKey === undefined ? {} : { "x-app-key": appKey },
  });
}

// Today's calendar day in Warsaw, the household's day (the app validates purchase dates against it).
const todayInWarsaw = new Intl.DateTimeFormat("en-CA", { timeZone: "Europe/Warsaw" }).format(new Date());

// Steps on a group need its id; without it they fail instead of silently requesting /groups/undefined.
function postExpense(groupIndex, form) {
  if (groupIds[groupIndex] === undefined) {
    return Promise.resolve({
      status: 0,
      location: `(group ${groupIndex === 0 ? "A" : "B"} was not created)`,
      body: "",
    });
  }
  return request(`/api/groups/${groupIds[groupIndex]}/expenses`, { method: "POST", form });
}

function checkExpenseLocation(groupIndex, suffix = "") {
  return (actual) =>
    actual.location === `/groups/${groupIds[groupIndex]}${suffix}` ? true : `location is ${actual.location}`;
}

function checkGoogleRedirect(actual, cookies) {
  let url;
  try {
    url = new URL(actual.location);
  } catch {
    return `location is not an absolute URL: ${actual.location}`;
  }
  if (!url.pathname.endsWith("/auth/v1/authorize")) return `unexpected path ${url.pathname}`;
  if (url.searchParams.get("provider") !== "google") return `provider=${url.searchParams.get("provider")}`;
  const redirectTo = url.searchParams.get("redirect_to");
  if (redirectTo !== `${BASE_URL}/auth/callback`) return `redirect_to=${redirectTo}`;
  const method = url.searchParams.get("code_challenge_method");
  if (method !== "s256") return `code_challenge_method=${method}`;
  if (![...cookies.keys()].some((name) => name.endsWith("-auth-token-code-verifier"))) {
    return "no *-auth-token-code-verifier cookie set";
  }
  return true;
}

const steps = [
  ["home renders", () => request("/"), { status: 200 }],
  ["privacy page renders", () => request("/privacy"), { status: 200 }],
  [
    "google signin redirects to Supabase authorize",
    () => request("/api/auth/google", { method: "POST" }),
    { status: 302, check: checkGoogleRedirect },
  ],
  [
    "callback reports cancelled provider consent",
    () => request("/auth/callback?error=access_denied&error_description="),
    { status: 302, location: "/auth/signin?error=Sign-in%20was%20cancelled" },
  ],
  ["dashboard redirects anonymous user", () => request("/dashboard"), { status: 302, location: "/auth/signin" }],
  [
    "signup creates account",
    () => request("/api/auth/signup", { method: "POST", form: { email, password } }),
    { status: 302, location: "/auth/confirm-email" },
  ],
  [
    "signin rejects wrong password",
    () => request("/api/auth/signin", { method: "POST", form: { email, password: "wrong" } }),
    { status: 302, location: "/auth/signin?error=" },
  ],
  [
    "signin accepts correct password",
    () => request("/api/auth/signin", { method: "POST", form: { email, password } }),
    { status: 302, location: "/dashboard" },
  ],
  ["dashboard renders for signed-in user", () => request("/dashboard"), { status: 200 }],
  [
    "dashboard shows the create-group form",
    () => request("/dashboard"),
    { status: 200, check: bodyContains('action="/api/groups"') },
  ],
  [
    "blank group name is rejected",
    () => request("/api/groups", { method: "POST", form: { name: "   " } }),
    { status: 302, location: "/dashboard?error=invalid_group_name" },
  ],
  [
    "create group A redirects to its page",
    () => request("/api/groups", { method: "POST", form: { name: groupA } }),
    { status: 302, check: checkNewGroupPage },
  ],
  ["group A page shows its name", requestGroupA, { status: 200, check: bodyContains(groupA) }],
  [
    "generate invite redirects to the group page",
    generateInviteA,
    { status: 302, check: (actual) => checkInviteGroupPage(groupIds[0])(actual) },
  ],
  ["group page shows the invite link once", requestGroupA, { status: 200, check: checkInviteShown }],
  ["invite link is not shown again", requestGroupA, { status: 200, check: checkInviteHidden }],
  [
    "create group B redirects to a different page",
    () => request("/api/groups", { method: "POST", form: { name: groupB } }),
    { status: 302, check: checkNewGroupPage },
  ],
  ["dashboard lists both groups", () => request("/dashboard"), { status: 200, check: bodyContains(groupA, groupB) }],
  ["unknown group returns 404", () => request(`/groups/${randomUUID()}`), { status: 404 }],
  ["signout clears session", () => request("/api/auth/signout", { method: "POST" }), { status: 302, location: "/" }],
  ["dashboard redirects after signout", () => request("/dashboard"), { status: 302, location: "/auth/signin" }],
  ["group page redirects after signout", requestGroupA, { status: 302, location: "/auth/signin" }],
  ["generate invite redirects after signout", generateInviteA, { status: 302, location: "/auth/signin" }],
  [
    "create group redirects after signout",
    () => request("/api/groups", { method: "POST", form: { name: groupA } }),
    { status: 302, location: "/auth/signin" },
  ],
  [
    "anonymous invite link leads to sign-in",
    () => requestInvite("/invite/<token>"),
    { status: 302, location: "/auth/signin", check: checkPendingInviteCookie },
  ],
  [
    "sign-in page mentions the invite",
    () => request("/auth/signin"),
    { status: 200, check: bodyContains("Sign in or create an account to accept your invite.") },
  ],
  [
    "second user signs up",
    () => request("/api/auth/signup", { method: "POST", form: { email: email2, password } }),
    { status: 302, location: "/auth/confirm-email" },
  ],
  [
    "second user signs in back to the invite",
    () => request("/api/auth/signin", { method: "POST", form: { email: email2, password } }),
    { status: 302, check: checkInviteLocation() },
  ],
  [
    "invite page shows the group name",
    () => requestInvite("/invite/<token>"),
    { status: 200, check: bodyContains(groupA) },
  ],
  [
    "joining lands on the group page",
    () => requestInvite("/api/invites/redeem", { method: "POST", form: { token: inviteToken } }),
    { status: 302, check: checkGroupALocation },
  ],
  ["new member sees the group", requestGroupA, { status: 200, check: bodyContains(groupA) }],
  [
    "used invite is rejected",
    () => requestInvite("/api/invites/redeem", { method: "POST", form: { token: inviteToken } }),
    { status: 302, check: checkInviteLocation("?error=invite_invalid") },
  ],
  ["used invite page returns 404", () => requestInvite("/invite/<token>"), { status: 404 }],
  ["unknown invite returns 404", () => request(`/invite/${randomBytes(32).toString("base64url")}`), { status: 404 }],
  [
    "second user adds an expense",
    () => postExpense(0, { title: "Czynsz", amount: "400,00", purchasedOn: todayInWarsaw }),
    { status: 302, check: checkExpenseLocation(0) },
  ],
  [
    "group page shows the expense and the debt",
    requestGroupA,
    { status: 200, check: bodyContains("Czynsz", "200,00") },
  ],
  [
    "invalid amount is rejected",
    () => postExpense(0, { title: "Czynsz", amount: "abc", purchasedOn: todayInWarsaw }),
    { status: 302, check: checkExpenseLocation(0, "?expenseError=invalid_amount") },
  ],
  [
    "non-member cannot add an expense to another group",
    () => postExpense(1, { title: "Czynsz", amount: "400,00", purchasedOn: todayInWarsaw }),
    { status: 302, check: checkExpenseLocation(1, "?expenseError=group_not_found") },
  ],
  ["second user signs out", () => request("/api/auth/signout", { method: "POST" }), { status: 302, location: "/" }],
  [
    "anonymous join redirects to sign-in",
    () => request("/api/invites/redeem", { method: "POST", form: { token: inviteToken ?? "" } }),
    { status: 302, location: "/auth/signin" },
  ],
  [
    "anonymous expense redirects to sign-in",
    () => postExpense(0, { title: "Czynsz", amount: "400,00", purchasedOn: todayInWarsaw }),
    { status: 302, location: "/auth/signin" },
  ],
  [
    "first user signs in again",
    () => request("/api/auth/signin", { method: "POST", form: { email, password } }),
    { status: 302, location: "/dashboard" },
  ],
  ["first user sees the amount they owe", requestGroupA, { status: 200, check: bodyContains("You owe", "200,00") }],
  ["first user signs out", () => request("/api/auth/signout", { method: "POST" }), { status: 302, location: "/" }],
  [
    "signed-in user calling an RPC directly without the app key is refused",
    () => firstUserCallsDirectly(),
    { status: 403, check: bodyContains('"code":"APPGATE"') },
  ],
  [
    "signed-in user calling an RPC directly with a wrong key is refused",
    () => firstUserCallsDirectly("not-the-app-key"),
    { status: 403, check: bodyContains('"code":"APPGATE"') },
  ],
  // Positive control: the same call with the app's key reaches the function and returns the user's data.
  [
    "the same call with the app key gets data",
    () => firstUserCallsDirectly(SUPABASE_APP_KEY),
    { status: 200, check: bodyContains(groupA) },
  ],
];

let failed = 0;
for (const [name, run, expected] of steps) {
  const actual = await run();
  const checkResult = expected.check ? expected.check(actual, jar) : true;
  const ok =
    actual.status === expected.status &&
    (expected.location === undefined || actual.location.startsWith(expected.location)) &&
    checkResult === true;
  console.log(`${ok ? "PASS" : "FAIL"}  ${name}  -> ${actual.status} ${actual.location}`);
  if (!ok) {
    failed++;
    console.log(`      expected ${expected.status} ${expected.location ?? ""}`);
    if (checkResult !== true) console.log(`      check failed: ${checkResult}`);
  }
}

console.log(failed ? `\n${failed} step(s) failed` : "\nAll smoke steps passed");
process.exit(failed ? 1 : 0);
